# -*- coding: utf-8 -*-
"""ABHI_TASK1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cC9IXTLVvqJgszmIpgOeiqtGFW4qkQF1
"""

from google.colab import drive
drive.mount('/content/gdrive')



"""**TASK-1 : TITANIC SURVIVAL PREDICTION**
Name: Abhishek Barai
Batch:July
Domain: Data Science
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""***Importing Dataset***"""

df = pd.read_csv('/content/gdrive/MyDrive/Colab Notebooks/Titanic-Dataset.csv')
df.head(10)

df.shape

df.describe()

"""***FEW MISSING VALUES IN AGE COLUMN***"""

df['Survived'].value_counts()

sns.countplot(x=df['Survived'], hue=df['Pclass'])

df["Sex"]

sns.countplot(x=df['Sex'], hue=df['Survived'])

# SURVIVAL RATE BY SEX
df.groupby('Sex')[['Survived']].mean()

df['Sex'].unique()

from sklearn.preprocessing import LabelEncoder
lebelencoder = LabelEncoder()

df['Sex']= lebelencoder.fit_transform(df['Sex'])
df.head()

df['Sex'], df['Survived']

sns.countplot(x=df['Sex'], hue=df['Survived'])

df.isna().sum()

# AFTER DROPPING NO COLUMN REQUIRED\
df=df.drop(['Age'], axis=1)

df_final = df
df_final.head()

x= df[['Pclass', 'Sex']]
y= df['Survived']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

from sklearn.linear_model import LogisticRegression

log= LogisticRegression(random_state = 0)
log.fit(x_train, y_train)

"""***MODEL PREDICTION***"""

pred = print(log.predict(x_test))

print(y_test)

import warnings
warnings.filterwarnings('ignore')

res= log.predict([[2,0]])

if(res==0):
  print("Not Survived")
else:
  print("Survived")

"""***Task Finished***"""